import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  keyboardArea: {
    flex: 1,
  },
  normativeWarning: {
    backgroundColor: '#FFF7ED',
    borderColor: '#C2410C',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  normativeWarningText: {
    color: '#7C2D12',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  normativePendingText: {
    color: '#9A3412',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  container: {
    flex: 1,
    backgroundColor: '#E8F0FF',
  },
  containerDark: {
    backgroundColor: '#07111F',
  },
  textDark: {
    color: '#F1F5F9',
  },
  textMutedDark: {
    color: '#C2D4E8',
  },
  inputDark: {
    backgroundColor: '#122A47',
    borderColor: '#365D88',
    color: '#F1F5F9',
  },
  subtleSurfaceDark: {
    backgroundColor: '#173252',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 164,
  },
  scrollContentDark: {
    backgroundColor: '#07111F',
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#D7E5FF',
    shadowColor: '#0B2653',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroCardDark: {
    backgroundColor: '#0F2340',
    borderColor: '#274D7F',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  heroBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#214EAB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroBadgeText: {
    fontSize: 22,
  },
  togglePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#EEF3FF',
  },
  togglePillDark: {
    backgroundColor: '#173252',
  },
  togglePillText: {
    color: '#214EAB',
    fontWeight: '700',
    fontSize: 12,
  },
  togglePillTextDark: {
    color: '#E2F1FF',
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0B2653',
    marginBottom: 6,
  },
  titleDark: {
    color: '#E2F1FF',
  },
  subtitle: {
    fontSize: 15,
    color: '#324A6E',
    marginBottom: 18,
  },
  subtitleDark: {
    color: '#A9C4E0',
  },
  heroMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricChip: {
    backgroundColor: '#F2F7FF',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    minWidth: 112,
  },
  metricChipDark: {
    backgroundColor: '#173252',
  },
  metricValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#214EAB',
  },
  metricValueDark: {
    color: '#E2F1FF',
  },
  metricLabel: {
    fontSize: 12,
    color: '#4A5568',
    marginTop: 2,
  },
  metricLabelDark: {
    color: '#A9C4E0',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0B2653',
    marginBottom: 10,
  },
  sectionText: {
    fontSize: 14,
    color: '#3D5A7A',
    lineHeight: 20,
    marginBottom: 14,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardDark: {
    backgroundColor: '#0F2340',
    shadowColor: '#020617',
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0B2653',
    marginBottom: 10,
  },
  cardDescription: {
    fontSize: 13,
    color: '#475A75',
    marginBottom: 10,
  },
  cardSource: {
    fontSize: 12,
    color: '#6B7A8F',
  },
  input: {
    backgroundColor: '#F9FBFF',
    borderRadius: 14,
    padding: 14,
    fontSize: 15,
    color: '#1D3147',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#D2E0FC',
  },
  multilineInput: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#214EAB',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonSecondary: {
    backgroundColor: '#F4F6FB',
  },
  buttonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  buttonTextSecondary: {
    color: '#214EAB',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  vesselTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  typeButton: {
    backgroundColor: '#EEF3FF',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 10,
    marginBottom: 10,
    minHeight: 48,
    justifyContent: 'center',
  },
  typeButtonActive: {
    backgroundColor: '#214EAB',
  },
  typeButtonText: {
    color: '#214EAB',
    fontSize: 13,
    fontWeight: '700',
  },
  typeButtonTextActive: {
    color: '#FFFFFF',
  },
  progressText: {
    fontSize: 13,
    color: '#314F78',
    marginBottom: 10,
  },
  checklistBlock: {
    backgroundColor: '#F7F9FF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  checklistItemText: {
    fontSize: 14,
    color: '#1D3147',
    fontWeight: '700',
    marginBottom: 6,
  },
  checklistReference: {
    fontSize: 12,
    color: '#5B6E8F',
    marginBottom: 10,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  statusButton: {
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    minHeight: 44,
    justifyContent: 'center',
  },
  statusButtonOutline: {
    backgroundColor: '#E8EEF8',
  },
  statusButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusButtonTextActive: {
    color: '#FFFFFF',
  },
  statusButtonTextOutline: {
    color: '#314F78',
  },
  quickQuestionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  quickQuestionChip: {
    backgroundColor: '#EEF3FF',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 10,
    marginBottom: 10,
    minHeight: 44,
    justifyContent: 'center',
  },
  quickQuestionText: {
    fontSize: 12,
    color: '#214EAB',
    fontWeight: '700',
  },
  resultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginTop: 10,
  },
  resultCardDark: {
    backgroundColor: '#0F2340',
    shadowColor: '#020617',
  },
  resultTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0B2653',
    marginBottom: 10,
  },
  resultText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  citationsList: {
    marginTop: 14,
  },
  citationTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0B2653',
    marginTop: 8,
    marginBottom: 8,
  },
  citationBlock: {
    backgroundColor: '#F1F5FF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  citationExcerpt: {
    fontSize: 13,
    color: '#2D3748',
    marginBottom: 8,
  },
  citationSource: {
    fontSize: 12,
    color: '#4A5568',
  },
  summaryList: {
    marginTop: 14,
  },
  summaryItem: {
    backgroundColor: '#F1F5FF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  summaryItemTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0B2653',
    marginBottom: 6,
  },
  summaryItemDetail: {
    fontSize: 12,
    color: '#475569',
    lineHeight: 18,
  },
  publicationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  publicationCardDark: {
    backgroundColor: '#0F2340',
    shadowColor: '#020617',
  },
  publicationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B2653',
    marginBottom: 6,
  },
  publicationSource: {
    fontSize: 12,
    color: '#4A5568',
    marginBottom: 6,
  },
  publicationNote: {
    fontSize: 13,
    color: '#334155',
    marginBottom: 12,
  },
  publicationMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  publicationBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    backgroundColor: '#214EAB',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pdfButton: {
    backgroundColor: '#214EAB',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    minHeight: 48,
    justifyContent: 'center',
  },
  pdfButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  filterButton: {
    backgroundColor: '#F4F6FB',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 10,
    marginBottom: 10,
    minHeight: 44,
    justifyContent: 'center',
  },
  filterButtonActive: {
    backgroundColor: '#214EAB',
  },
  filterButtonText: {
    color: '#214EAB',
    fontSize: 12,
    fontWeight: '700',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
  },
  previewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    marginTop: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  previewCardDark: {
    backgroundColor: '#0F2340',
    shadowColor: '#020617',
  },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  previewTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B2653',
    flex: 1,
    marginRight: 12,
  },
  closePreviewButton: {
    backgroundColor: '#EEF3FF',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  closePreviewButtonText: {
    color: '#214EAB',
    fontWeight: '700',
  },
  previewFrame: {
    width: '100%',
    height: 480,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D2E0FC',
  },
  bottomTabBar: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 8,
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 7,
    paddingVertical: 8,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D8EE',
    shadowColor: '#0B2653',
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  bottomTabBarDark: {
    backgroundColor: '#0B1730',
    borderColor: '#284A73',
    shadowColor: '#000000',
  },
  bottomTabTouchTarget: {
    flex: 1,
    minHeight: 60,
    justifyContent: 'center',
  },
  bottomTabContent: {
    minHeight: 58,
    marginHorizontal: 2,
    paddingHorizontal: 2,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bottomTabContentActive: {
    backgroundColor: '#E5EFFF',
  },
  bottomTabContentDark: {
    backgroundColor: 'transparent',
  },
  bottomTabContentActiveDark: {
    backgroundColor: '#183F6D',
  },
  bottomTabIndicator: {
    position: 'absolute',
    top: 0,
    width: 34,
    height: 4,
    borderRadius: 4,
    backgroundColor: '#1769AA',
  },
  bottomTabLabel: {
    color: '#607089',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  bottomTabLabelDark: {
    color: '#A9C4E0',
  },
  bottomTabLabelActive: {
    color: '#14558D',
    fontWeight: '800',
  },
  bottomTabLabelActiveDark: {
    color: '#A9D8FF',
  },
});
